---

- name: config > PostgreSQL configuration
  template:
    src: "{{ manala_postgresql_config_template }}"
    dest: /etc/postgresql/{{ manala_postgresql_version }}/main/postgresql.conf
  when: manala_postgresql_config_template is not none
  notify:
    - postgresql restart

- name: config > PostgreSQL host-based authentication (hba) configuration
  template:
    src: "{{ manala_postgresql_config_hba_template }}"
    dest: /etc/postgresql/{{ manala_postgresql_version }}/main/pg_hba.conf
  when: manala_postgresql_config_hba_template is not none
  notify:
    - postgresql restart
