---

- name: privileges > Requirements
  apt:
    name: python-psycopg2
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  when: manala_postgresql_privileges|length > 0

- name: privileges > Handle
  postgresql_user:
    name:       "{{ item.role }}"
    priv:       "{{ item.privileges|join(',') }}"
    db:         "{{ item.database }}"
    state:      "{{ item.state|default('present') }}"
    login_host: "{{ manala_postgresql_login_host }}"
  with_items: "{{ manala_postgresql_privileges }}"
